<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="JD" failures="2" tests="8" name="RetryFailedTestCases" time="0.128" errors="0" timestamp="2021-03-17T22:22:52 IST">
  <testcase classname="selenium_RetryFailedTestCases.MyClassOne" name="testOne" time="0.016"/>
  <testcase classname="selenium_RetryFailedTestCases.MyClassOne" name="testTwo" time="0.005">
    <skipped/>
  </testcase> <!-- testTwo -->
  <testcase classname="selenium_RetryFailedTestCases.MyClassOne" name="testTwo" time="0.003">
    <skipped/>
  </testcase> <!-- testTwo -->
  <testcase classname="selenium_RetryFailedTestCases.MyClassOne" name="testTwo" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at selenium_RetryFailedTestCases.MyClassOne.testTwo(MyClassOne.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testTwo -->
  <testcase classname="selenium_RetryFailedTestCases.MyClassTwo" name="testFour" time="0.003">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="selenium_RetryFailedTestCases.MyClassTwo" name="testFour" time="0.001">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="selenium_RetryFailedTestCases.MyClassTwo" name="testFour" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at selenium_RetryFailedTestCases.MyClassTwo.testFour(MyClassTwo.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testFour -->
  <testcase classname="selenium_RetryFailedTestCases.MyClassTwo" name="testfive" time="0.008"/>
</testsuite> <!-- RetryFailedTestCases -->
